[0m13:29:06.316817 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049e19d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1059998e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049e1910>]}


============================== 13:29:06.326230 | 04967fda-3922-4196-8cc9-185c6fb4fb5e ==============================
[0m13:29:06.326230 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:29:06.326771 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/jordi.vidaldellobatera/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt seed', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:29:06.327259 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordi.vidaldellobatera/Documents/repos_personal/dbt-tutorial/jaffle-data/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:29:06.327792 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.15346271, "process_in_blocks": "0", "process_kernel_time": 0.495513, "process_mem_max_rss": "91815936", "process_out_blocks": "0", "process_user_time": 1.495527}
[0m13:29:06.328157 [debug] [MainThread]: Command `dbt seed` failed at 13:29:06.328086 after 0.15 seconds
[0m13:29:06.328449 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105999430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105999730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10599b410>]}
[0m13:29:06.328703 [debug] [MainThread]: Flushing usage events
[0m13:29:06.858636 [debug] [MainThread]: An error was encountered while trying to flush usage events
